version: "3.3"
services:
  db:
    image: vsouza/dynamo-local
    ports:
      - 8080:8080
    command: --port 8080

  web:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile

    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"
    ports:
      - 8888:8888
    volumes:
      - ~/.gitconfig:/root/.gitconfig
      - ..:/code
    depends_on:
      - db
