server:
  port: 0.0.0.0:8888

jwt:
  secret: RobertIsSoHandsome
  expiration: 65536

hmac:
  key: "RobertIsHandsome"

http:
  auth:
    secret: 大表格

db:
  region: us
  endpoint: 172.18.0.2:8080
  disable_ssl: true
